/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_ayatana_Launcher */

#ifndef _Included_org_java_ayatana_Launcher
#define _Included_org_java_ayatana_Launcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_ayatana_Launcher
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    _setProgressVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher__1setProgressVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    isProgressVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_ayatana_Launcher_isProgressVisible
  (JNIEnv *, jobject);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    _setProgressValue
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher__1setProgressValue
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    getProgressValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_java_ayatana_Launcher_getProgressValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
