/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_ayatana_GMainLoop */

#ifndef _Included_org_java_ayatana_GMainLoop
#define _Included_org_java_ayatana_GMainLoop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_ayatana_GMainLoop
 * Method:    runGMainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_GMainLoop_runGMainLoop
  (JNIEnv *, jclass);

/*
 * Class:     org_java_ayatana_GMainLoop
 * Method:    quitGMainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_GMainLoop_quitGMainLoop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
