/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_ayatana_Launcher */

#ifndef _Included_org_java_ayatana_Launcher
#define _Included_org_java_ayatana_Launcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_ayatana_Launcher
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    setNativeCount
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher_setNativeCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    setNativeCountVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher_setNativeCountVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    setNativeProgress
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher_setNativeProgress
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    setNativeProgressVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher_setNativeProgressVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    setNativeUrgent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_Launcher_setNativeUrgent
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    getCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_java_ayatana_Launcher_getCount
  (JNIEnv *, jobject);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    isCountVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_ayatana_Launcher_isCountVisible
  (JNIEnv *, jobject);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    getProgress
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_java_ayatana_Launcher_getProgress
  (JNIEnv *, jobject);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    isProgressVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_ayatana_Launcher_isProgressVisible
  (JNIEnv *, jobject);

/*
 * Class:     org_java_ayatana_Launcher
 * Method:    isUrgent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_java_ayatana_Launcher_isUrgent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
