/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jarego_jayatana_basic_GlobalMenu */

#ifndef _Included_com_jarego_jayatana_basic_GlobalMenu
#define _Included_com_jarego_jayatana_basic_GlobalMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_uninitialize
  (JNIEnv *, jclass);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    getWindowXID
 * Signature: (Ljava/awt/Window;)J
 */
JNIEXPORT jlong JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_getWindowXID
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    setWindowXID
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_setWindowXID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    registerWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_registerWatcher
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    unregisterWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_unregisterWatcher
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    addMenu
 * Signature: (JILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_addMenu
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    addMenuItem
 * Signature: (JILjava/lang/String;ZII)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_addMenuItem
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean, jint, jint);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    addMenuItemRadio
 * Signature: (JILjava/lang/String;ZIIZ)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_addMenuItemRadio
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean, jint, jint, jboolean);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    addMenuItemCheck
 * Signature: (JILjava/lang/String;ZIIZ)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_addMenuItemCheck
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean, jint, jint, jboolean);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    addSeparator
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_addSeparator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jarego_jayatana_basic_GlobalMenu
 * Method:    removeAllMenus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jarego_jayatana_basic_GlobalMenu_removeAllMenus
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
