/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_ayatana_ApplicationMenu */

#ifndef _Included_org_java_ayatana_ApplicationMenu
#define _Included_org_java_ayatana_ApplicationMenu
#ifdef __cplusplus
extern "C" {
#endif
#undef org_java_ayatana_ApplicationMenu_TOGGLE_TYPE_RADIO
#define org_java_ayatana_ApplicationMenu_TOGGLE_TYPE_RADIO 0L
#undef org_java_ayatana_ApplicationMenu_TOGGLE_TYPE_CHECK
#define org_java_ayatana_ApplicationMenu_TOGGLE_TYPE_CHECK 1L
#undef org_java_ayatana_ApplicationMenu_TOGGLE_STATE_CHECKED
#define org_java_ayatana_ApplicationMenu_TOGGLE_STATE_CHECKED 0L
#undef org_java_ayatana_ApplicationMenu_TOGGLE_STATE_UNCHECKED
#define org_java_ayatana_ApplicationMenu_TOGGLE_STATE_UNCHECKED 1L
/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_uninitialize
  (JNIEnv *, jclass);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    registerWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_registerWatcher
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    unregisterWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_unregisterWatcher
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    getWindowXID
 * Signature: (Ljava/awt/Window;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_ayatana_ApplicationMenu_getWindowXID
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    addMenu
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_addMenu
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    addSeparator
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_addSeparator
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    setMenuItemLabel
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_setMenuItemLabel
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    setMenuItemAccelerator
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_setMenuItemAccelerator
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    setMenuItemToggleType
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_setMenuItemToggleType
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    setMenuItemToggleState
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_setMenuItemToggleState
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    removeMenuItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_removeMenuItem
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
