/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_java_ayatana_ApplicationMenu */

#ifndef _Included_org_java_ayatana_ApplicationMenu
#define _Included_org_java_ayatana_ApplicationMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    nativeInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_nativeInitialize
  (JNIEnv *, jclass);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    nativeUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_nativeUninitialize
  (JNIEnv *, jclass);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    getWindowXID
 * Signature: (Ljava/awt/Window;)J
 */
JNIEXPORT jlong JNICALL Java_org_java_ayatana_ApplicationMenu_getWindowXID
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    registerWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_registerWatcher
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    unregisterWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_unregisterWatcher
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    addMenu
 * Signature: (JILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_addMenu
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    removeAll
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_removeAll
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    removeAllItems
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_removeAllItems
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    addMenuItem
 * Signature: (JILjava/lang/String;ZII)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_addMenuItem
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean, jint, jint);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    addMenuItemRadio
 * Signature: (JILjava/lang/String;ZIIZ)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_addMenuItemRadio
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean, jint, jint, jboolean);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    addMenuItemCheck
 * Signature: (JILjava/lang/String;ZIIZ)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_addMenuItemCheck
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean, jint, jint, jboolean);

/*
 * Class:     org_java_ayatana_ApplicationMenu
 * Method:    addMenuItemSeparator
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_java_ayatana_ApplicationMenu_addMenuItemSeparator
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
